import { Ingredient, Recipe } from './types';

export const INGREDIENTS: Ingredient[] = [
  // Veggies
  { id: 'kimchi', name: '김치', category: 'veggie', isPopular: true, emoji: '🥬', imageUrl: '/kimchi_icon.png' },
  { id: 'onion', name: '양파', category: 'veggie', isPopular: true, emoji: '🧅' },
  { id: 'green_onion', name: '대파', category: 'veggie', isPopular: true, emoji: '🎋', imageUrl: '/green_onion_icon.png' },
  { id: 'garlic', name: '다진마늘', category: 'veggie', isEssential: true, emoji: '🧄' },
  { id: 'potato', name: '감자', category: 'veggie', emoji: '🥔' },
  { id: 'carrot', name: '당근', category: 'veggie', emoji: '🥕' },
  { id: 'zucchini', name: '애호박', category: 'veggie', emoji: '🥒' },
  { id: 'bean_sprout', name: '콩나물', category: 'veggie', emoji: '🌱', imageUrl: '/bean_sprout_icon.png' },
  { id: 'tofu', name: '두부', category: 'veggie', isPopular: true, emoji: '🧊' },
  { id: 'radish', name: '무', category: 'veggie', emoji: '🥔' }, // Alternative if no exact radish emoji
  { id: 'mushroom', name: '버섯', category: 'veggie', emoji: '🍄' },
  { id: 'cucumber', name: '오이', category: 'veggie', emoji: '🥒' },
  { id: 'spinach', name: '시금치', category: 'veggie', emoji: '🌿' },
  { id: 'cabbage', name: '양배추', category: 'veggie', emoji: '🥬' },
  { id: 'strawberry', name: '딸기', category: 'veggie', emoji: '🍓', isPopular: true },
  { id: 'lettuce', name: '양상추', category: 'veggie', emoji: '🥬' },
  { id: 'broccoli', name: '브로콜리', category: 'veggie', emoji: '🥦' },


  // Meat
  { id: 'pork_belly', name: '돼지고기(삼겹살)', category: 'meat', emoji: '🥓' },
  { id: 'pork_shoulder', name: '돼지고기(목살/찌개용)', category: 'meat', emoji: '🥩' },
  { id: 'beef', name: '소고기', category: 'meat', emoji: '🍖' },
  { id: 'spam', name: '스팸/햄', category: 'meat', emoji: '🥫' },
  { id: 'smoked_duck', name: '훈제오리', category: 'meat', emoji: '🦆' },
  { id: 'egg', name: '계란', category: 'meat', isPopular: true, emoji: '🥚' },
  { id: 'chicken', name: '닭고기', category: 'meat', emoji: '🍗' },
  { id: 'minced_pork', name: '다짐육(돼지)', category: 'meat', emoji: '🥩' },

  // Seafood
  { id: 'tuna_can', name: '참치캔', category: 'seafood', isPopular: true, emoji: '🐟', imageUrl: '/canned_tuna_icon.png' },
  { id: 'anchovy', name: '멸치', category: 'seafood', emoji: '🐟', imageUrl: '/dried_anchovy_icon.png' },
  { id: 'squid', name: '오징어', category: 'seafood', emoji: '🦑' },
  { id: 'fish_cake', name: '어묵', category: 'seafood', isPopular: true, emoji: '🍢' },
  { id: 'shrimp', name: '새우', category: 'seafood', emoji: '🦐' },
  { id: 'flatfish', name: '광어', category: 'seafood', emoji: '🐟' },
  { id: 'spanish_mackerel', name: '삼치', category: 'seafood', emoji: '🐟' },

  // Seasoning (Essentials)
  { id: 'gochujang', name: '고추장', category: 'seasoning', isEssential: true, emoji: '🌶️' },
  { id: 'soy_sauce', name: '간장', category: 'seasoning', isEssential: true, emoji: '🍶' },
  { id: 'sugar', name: '설탕', category: 'seasoning', isEssential: true, emoji: '🧂' },
  { id: 'sesame_oil', name: '참기름', category: 'seasoning', isEssential: true, emoji: '🧴' },
  { id: 'salt', name: '소금', category: 'seasoning', isEssential: true, emoji: '🧂' },
  { id: 'pepper', name: '후추', category: 'seasoning', isEssential: true, emoji: '🧂' },
  { id: 'gochugaru', name: '고춧가루', category: 'seasoning', isEssential: true, emoji: '🌶️' },
  { id: 'mustard', name: '겨자', category: 'seasoning', emoji: '🟡' },
  { id: 'citron_syrup', name: '유자청', category: 'seasoning', emoji: '🍯' },

  // Grain
  { id: 'rice', name: '밥', category: 'grain', emoji: '🍚', isPopular: true },
  { id: 'noodle', name: '국수면', category: 'grain', emoji: '🍜' },
  { id: 'ramen', name: '라면', category: 'grain', emoji: '🍜', isPopular: true },
  { id: 'rice_cake', name: '떡', category: 'grain', isPopular: true, emoji: '🍡' },

  // Dairy
  { id: 'cheese', name: '치즈', category: 'dairy' },
  { id: 'milk', name: '우유', category: 'dairy' },
];

import EXTERNAL_DATA from './data/external_recipes.json';

// Type assertion for external data
const EXTERNAL_RECIPES = (EXTERNAL_DATA as unknown) as Recipe[];

export const RECIPES: Recipe[] = [
  ...EXTERNAL_RECIPES,
  {
    id: 'kimchi_stew',
    title: '돼지고기 김치찌개',
    description: '한국인의 소울푸드. 푹 익은 김치와 돼지고기의 환상 조합.',
    cookingTimeMinutes: 30,
    difficulty: 'Medium',
    imageUrl: '/pork_kimchi_stew.png',
    ingredients: [
      { id: 'kimchi', amount: '1/4 포기', required: true },
      { id: 'pork_shoulder', amount: '200g', required: true },
      { id: 'tofu', amount: '1/2 모', required: false },
      { id: 'green_onion', amount: '1대', required: false },
      { id: 'garlic', amount: '1T', required: true },
      { id: 'gochugaru', amount: '1T', required: true },
      { id: 'soy_sauce', amount: '1T', required: true },
    ],
    instructions: [
      '김치와 돼지고기를 먹기 좋은 크기로 썰어줍니다.',
      '냄비에 참기름을 두르고 김치와 돼지고기를 달달 볶습니다.',
      '고기가 어느 정도 익으면 물을 붓고 끓입니다.',
      '다진마늘, 고춧가루, 간장으로 간을 맞춥니다.',
      '마지막으로 두부와 대파를 넣고 한소끔 더 끓여내면 완성!',
    ],
    calories: 450,
    servingSize: 2,
    carbohydrates: 15,
    fat: 25,
    protein: 30,
  },
  {
    id: 'doenjang_stew',
    title: '구수한 된장찌개',
    description: '애호박, 두부, 감자를 넣고 보글보글 끓인 집밥의 정석.',
    cookingTimeMinutes: 25,
    difficulty: 'Medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Doenjang-jjigae.jpg?width=800',
    ingredients: [
      { id: 'tofu', amount: '1/2 모', required: true },
      { id: 'zucchini', amount: '1/3 개', required: true },
      { id: 'potato', amount: '1개', required: true },
      { id: 'onion', amount: '1/2개', required: true },
      { id: 'mushroom', amount: '조금', required: false },
      { id: 'green_onion', amount: '1대', required: false },
      { id: 'anchovy', amount: '5마리(육수용)', required: true },
      { id: 'garlic', amount: '0.5T', required: true },
    ],
    instructions: [
      '멸치 육수를 진하게 우려냅니다.',
      '된장을 체에 걸러 육수에 풀어줍니다.',
      '감자, 애호박, 양파를 깍둑썰기하여 넣고 끓입니다.',
      '야채가 익으면 두부, 버섯, 다진마늘을 넣습니다.',
      '마지막에 대파를 넣고 마무리합니다.',
    ],
    calories: 320,
    servingSize: 2,
    carbohydrates: 20,
    fat: 12,
    protein: 18,
  },
  {
    id: 'tteokbokki',
    title: '국물 떡볶이',
    description: '매콤달콤한 국민 간식. 어묵과 파를 듬뿍 넣어보세요.',
    cookingTimeMinutes: 20,
    difficulty: 'Easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tteokbokki.JPG?width=800',
    ingredients: [
      { id: 'rice_cake', amount: '200g', required: true },
      { id: 'fish_cake', amount: '2장', required: true },
      { id: 'green_onion', amount: '1대', required: true },
      { id: 'gochujang', amount: '2T', required: true },
      { id: 'sugar', amount: '2T', required: true },
      { id: 'gochugaru', amount: '1T', required: true },
      { id: 'soy_sauce', amount: '1T', required: true },
    ],
    instructions: [
      '떡은 물에 불려두고, 어묵과 대파는 썰어둡니다.',
      '팬에 물을 붓고 고추장, 설탕, 간장, 고춧가루를 풀어 끓입니다.',
      '국물이 끓어오르면 떡과 어묵을 넣습니다.',
      '국물이 걸쭉해질 때까지 졸이다가 대파를 넣고 마무리합니다.',
    ],
    calories: 650,
    servingSize: 2,
    carbohydrates: 120,
    fat: 8,
    protein: 14,
  },
  {
    id: 'spam_mayo',
    title: '스팸 마요 덮밥',
    description: '반찬 없을 때 최고! 짭조름한 스팸과 고소한 마요네즈.',
    cookingTimeMinutes: 15,
    difficulty: 'Easy',
    imageUrl: '/spam_mayo.png',
    ingredients: [
      { id: 'spam', amount: '1/2캔', required: true },
      { id: 'egg', amount: '2개', required: true },
      { id: 'rice', amount: '1공기', required: true },
      { id: 'onion', amount: '1/2개', required: false },
      { id: 'soy_sauce', amount: '1T', required: true },
      { id: 'sugar', amount: '0.5T', required: true },
    ],
    instructions: [
      '스팸은 깍둑썰기하여 노릇하게 굽습니다.',
      '계란은 스크램블 에그로 만듭니다.',
      '양파는 채 썰어 간장, 설탕과 함께 볶아 졸입니다.',
      '밥 위에 스크램블 에그, 볶은 양파, 스팸을 올립니다.',
      '마요네즈를 예쁘게 뿌려 완성합니다.',
    ],
    calories: 780,
    servingSize: 1,
    carbohydrates: 90,
    fat: 35,
    protein: 22,
  },
  {
    id: 'egg_roll',
    title: '폭신폭신 계란말이',
    description: '도시락 반찬 1위. 당근과 파를 넣어 식감을 살려보세요.',
    cookingTimeMinutes: 10,
    difficulty: 'Easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gyeran-mari_1.jpg?width=800',
    ingredients: [
      { id: 'egg', amount: '4개', required: true },
      { id: 'green_onion', amount: '조금', required: false },
      { id: 'carrot', amount: '조금', required: false },
      { id: 'salt', amount: '약간', required: true },
    ],
    instructions: [
      '계란을 풀고 소금으로 간을 합니다.',
      '다진 당근과 대파를 계란물에 섞습니다.',
      '달군 팬에 기름을 두르고 계란물을 얇게 붓습니다.',
      '반쯤 익으면 돌돌 말아가며 익히고, 남은 계란물을 부어가며 반복합니다.',
      '한 김 식힌 후 예쁘게 썰어냅니다.',
    ],
    calories: 280,
    servingSize: 2,
    carbohydrates: 2,
    fat: 20,
    protein: 24,
  },
  {
    id: 'bibimbap',
    title: '냉털 비빔밥',
    description: '냉장고 속 남은 나물과 야채를 털어넣고 고추장에 비벼드세요.',
    cookingTimeMinutes: 15,
    difficulty: 'Easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Bibimbap.jpg?width=800',
    ingredients: [
      { id: 'rice', amount: '1공기', required: true },
      { id: 'bean_sprout', amount: '한줌', required: false },
      { id: 'zucchini', amount: '1/4개', required: false },
      { id: 'carrot', amount: '1/4개', required: false },
      { id: 'egg', amount: '1개', required: true },
      { id: 'gochujang', amount: '1T', required: true },
      { id: 'sesame_oil', amount: '1T', required: true },
    ],
    instructions: [
      '야채들은 채 썰어 볶거나 데쳐서 준비합니다.',
      '계란은 써니사이드업으로 프라이합니다.',
      '그릇에 밥을 담고 준비한 야채를 둘러 담습니다.',
      '가운데 계란후라이를 올리고 고추장과 참기름을 뿌리면 완성!',
    ],
    calories: 550,
    servingSize: 1,
    carbohydrates: 85,
    fat: 15,
    protein: 18,
  },
  {
    id: 'tuna_kimchi_stew',
    title: '참치 김치찌개',
    description: '고기보다 깔끔한 맛을 원할 땐 참치!',
    cookingTimeMinutes: 20,
    difficulty: 'Easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tuna_kimchi-jjigae.jpg?width=800',
    ingredients: [
      { id: 'kimchi', amount: '1/4 포기', required: true },
      { id: 'tuna_can', amount: '1캔', required: true },
      { id: 'onion', amount: '1/2개', required: true },
      { id: 'sugar', amount: '0.5T', required: true },
      { id: 'garlic', amount: '1T', required: true },
    ],
    instructions: [
      '김치를 먹기 좋게 썰어 냄비에 볶습니다 (설탕을 조금 넣으면 신맛이 잡혀요).',
      '물을 붓고 끓이다가 김치가 익으면 참치와 양파를 넣습니다.',
      '다진마늘을 넣고 한소끔 더 끓여냅니다.',
      '부족한 간은 김치국물이나 소금으로 맞춥니다.',
    ],
    calories: 420,
    servingSize: 2,
    carbohydrates: 12,
    fat: 22,
    protein: 35,
  },
  {
    id: 'soyu_tteokbokki',
    title: '궁중 떡볶이 (간장)',
    description: '아이들도 잘 먹는 맵지 않은 단짠단짠 떡볶이.',
    cookingTimeMinutes: 25,
    difficulty: 'Medium',
    imageUrl: '/gungjung_tteokbokki.png',
    ingredients: [
      { id: 'rice_cake', amount: '200g', required: true },
      { id: 'beef', amount: '100g', required: true },
      { id: 'onion', amount: '1/2개', required: true },
      { id: 'mushroom', amount: '1줌', required: false },
      { id: 'soy_sauce', amount: '3T', required: true },
      { id: 'sugar', amount: '1T', required: true },
      { id: 'sesame_oil', amount: '1T', required: true },
    ],
    instructions: [
      '떡은 물에 불리고, 소고기는 간장/설탕/참기름으로 밑간합니다.',
      '야채는 먹기 좋은 크기로 썹니다.',
      '팬에 고기를 먼저 볶다가 야채와 떡을 넣고 함께 볶습니다.',
      '물을 약간 붓고 간장, 설탕으로 간을 맞추며 졸여냅니다.',
      '참기름을 둘러 마무리합니다.',
    ],
    calories: 580,
    servingSize: 2,
    carbohydrates: 95,
    fat: 14,
    protein: 20,
  },
  {
    id: 'strawberry_salad',
    title: '상큼한 스트로베리 샐러드',
    description: '제철 **딸기**와 아삭한 **양상추**가 어우러진 상큼한 샐러드.',
    cookingTimeMinutes: 10,
    difficulty: 'Easy',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    ingredients: [
      { id: 'strawberry', amount: '10개', required: true },
      { id: 'lettuce', amount: '1/2통', required: true },
      // User says they saw "Salt" (maybe confusion with milk or default?), let's stick to requested items + milk
      { id: 'milk', amount: '2T (요거트 대용)', required: false },
    ],
    instructions: [
      '딸기는 깨끗이 씻어 반으로 자릅니다.',
      '양상추는 한입 크기로 뜯어 씻어 물기를 뺍니다.',
      '그릇에 야채와 딸기를 담고 드레싱(우유/요거트 등)을 뿌려 완성합니다.',
    ],
    calories: 150,
    servingSize: 2,
    carbohydrates: 20,
    fat: 5,
    protein: 3,
  },

  {
    id: 'flatfish_steak',
    title: '부드러운 광어 스테이크',
    description: '담백한 **광어** 살을 버터에 구워 풍미를 더한 고급 요리.',
    cookingTimeMinutes: 25,
    difficulty: 'Medium',
    imageUrl: 'https://t1.daumcdn.net/cfile/tistory/242D554C547432C318',
    ingredients: [
      { id: 'flatfish', amount: '1마리 (필렛)', required: true },
      { id: 'salt', amount: '약간', required: true },
      { id: 'pepper', amount: '약간', required: true },
      { id: 'garlic', amount: '3쪽', required: false },
      // Butter implied but not in ingredients list yet, using oil implies standard frying or assume user implies butter
    ],
    instructions: [
      '광어 살에 소금, 후추로 밑간을 합니다.',
      '팬을 달구고 버터(또는 식용유)를 녹인 뒤 마늘을 볶아 향을 냅니다.',
      '광어를 넣어 앞뒤로 노릇하게 굽습니다.',
      '접시에 담고 구운 야채를 곁들입니다.',
    ],
    calories: 320,
    servingSize: 1,
    carbohydrates: 0,
    fat: 15,
    protein: 45,
  },
  {
    id: 'grilled_mackerel_yuja',
    title: '상큼한 유자 삼치구이',
    description: '담백한 **삼치** 구이와 향긋한 **유자청**의 완벽한 조화.',
    cookingTimeMinutes: 20,
    difficulty: 'Easy',
    imageUrl: 'https://recipe1.ezmember.co.kr/cache/recipe/2015/06/18/d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8_1.jpg',
    ingredients: [
      { id: 'spanish_mackerel', amount: '1/2마리', required: true },
      { id: 'citron_syrup', amount: '2T', required: true },
      { id: 'soy_sauce', amount: '1T', required: true },
      { id: 'salt', amount: '약간', required: true },
    ],
    instructions: [
      '삼치는 소금을 뿌려 10분간 재운 뒤 물기를 닦습니다.',
      '팬이나 오븐에서 삼치를 노릇하게 굽습니다.',
      '유자청과 간장을 섞어 소스를 만듭니다.',
      '구워진 삼치 위에 소스를 바르거나 곁들여 냅니다.',
    ],
    calories: 450,
    servingSize: 2,
    carbohydrates: 15,
    fat: 25,
    protein: 35,
  },
  {
    id: 'smoked_duck_salad',
    title: '훈제오리가슴살 샐러드',
    description: '쫄깃한 **훈제오리**와 신선한 야채가 어우러진 든든한 샐러드.',
    cookingTimeMinutes: 15,
    difficulty: 'Easy',
    imageUrl: 'https://recipe1.ezmember.co.kr/cache/recipe/2019/02/19/6a804791090176881768817688176881_1.jpg',
    ingredients: [
      { id: 'smoked_duck', amount: '200g', required: true },
      { id: 'lettuce', amount: '1/2통 (양상추/쌈채소)', required: true },
      { id: 'onion', amount: '1/4개', required: false },
      { id: 'mustard', amount: '1T', required: true },
      { id: 'soy_sauce', amount: '1T', required: true },
    ],
    instructions: [
      '훈제오리는 팬에 살짝 구워 기름기를 뺍니다.',
      '야채는 씻어 먹기 좋은 크기로 찢거나 썹니다.',
      '접시에 야채와 구운 오리를 담고 머스타드 소스(또는 오리엔탈 드레싱)를 곁들입니다.',
    ],
    calories: 320,
    servingSize: 2,
    carbohydrates: 10,
    fat: 25,
    protein: 20,
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  veggie: '🍅 채소/과일',
  meat: '🥩 육류/계란',
  seafood: '🐟 수산물',
  seasoning: '🧂 양념/소스',
  grain: '🍚 곡물/면/떡',
  dairy: '🧀 유제품',
};